export interface Project {
  title: string;
  slug: string;
  imagePath: string;
  client: string;
  tags: string[];
  year: number;
}

export const projects: Project[] = [
  { title: "CASAMIGOS GLOBAL TRAVEL",  slug: "casamigos-global-travel",  imagePath: "/images/01.jpg", client: "DIAGEO",      tags: ["CAMPAIGN", "ILLUSTRATION", "3D"],   year: 2025 },
  { title: "AIR MAX REVIVAL",          slug: "air-max-revival",          imagePath: "/images/02.jpg", client: "NIKE",        tags: ["IDENTITY", "MOTION", "RETAIL"],     year: 2025 },
  { title: "DIOR CRUISE LOOKBOOK",     slug: "dior-cruise-lookbook",     imagePath: "/images/03.jpg", client: "LVMH",        tags: ["EDITORIAL", "TYPOGRAPHY"],          year: 2024 },
  { title: "WRAPPED 2024",             slug: "wrapped-2024",             imagePath: "/images/04.jpg", client: "SPOTIFY",     tags: ["INTERACTIVE", "DATA VIZ", "WEB"],   year: 2024 },
  { title: "SPATIAL AUDIO LAUNCH",     slug: "spatial-audio-launch",     imagePath: "/images/05.jpg", client: "APPLE",       tags: ["UI/UX", "MOTION", "PRODUCT"],       year: 2024 },
  { title: "SF-23 REVEAL FILM",        slug: "sf23-reveal-film",         imagePath: "/images/06.jpg", client: "FERRARI",     tags: ["3D", "FILM", "CAMPAIGN"],           year: 2024 },
  { title: "X.O HERITAGE SERIES",      slug: "xo-heritage-series",       imagePath: "/images/07.jpg", client: "HENNESSY",    tags: ["ILLUSTRATION", "PACKAGING"],        year: 2023 },
  { title: "WEDNESDAY TITLE SEQ",      slug: "wednesday-title-seq",      imagePath: "/images/08.jpg", client: "NETFLIX",     tags: ["MOTION", "TYPE", "VFX"],            year: 2023 },
  { title: "PERPETUAL CAMPAIGN",       slug: "perpetual-campaign",       imagePath: "/images/09.jpg", client: "ROLEX",       tags: ["PHOTOGRAPHY", "PRINT", "OOH"],      year: 2023 },
  { title: "FUTURE OF SPORT",          slug: "future-of-sport",          imagePath: "/images/10.jpg", client: "ADIDAS",      tags: ["MOTION", "IDENTITY", "WEB"],        year: 2023 },
  { title: "SS24 CAMPAIGN",            slug: "ss24-campaign",            imagePath: "/images/11.jpg", client: "BALENCIAGA",  tags: ["EDITORIAL", "DIGITAL", "FILM"],     year: 2023 },
  { title: "RAMPAGE 2023",             slug: "rampage-2023",             imagePath: "/images/12.jpg", client: "RED BULL",    tags: ["MOTION", "SOCIAL", "EVENT"],        year: 2022 },
  { title: "BELOVED FRAGRANCE",        slug: "beloved-fragrance",        imagePath: "/images/13.jpg", client: "GUCCI",       tags: ["3D", "PACKAGING", "CAMPAIGN"],      year: 2022 },
  { title: "MAX 2022 IDENTITY",        slug: "max-2022-identity",        imagePath: "/images/14.jpg", client: "ADOBE",       tags: ["IDENTITY", "MOTION", "WEB"],        year: 2022 },
  { title: "TAYCAN CROSS TURISMO",     slug: "taycan-cross-turismo",     imagePath: "/images/15.jpg", client: "PORSCHE",     tags: ["FILM", "3D", "OOH"],                year: 2022 },
  { title: "NITRO ELITE LAUNCH",       slug: "nitro-elite-launch",       imagePath: "/images/16.jpg", client: "PUMA",        tags: ["MOTION", "RETAIL", "SOCIAL"],       year: 2022 },
  { title: "GALAXY FOLD 4",            slug: "galaxy-fold-4",            imagePath: "/images/17.jpg", client: "SAMSUNG",     tags: ["UI/UX", "PRODUCT", "DIGITAL"],      year: 2021 },
  { title: "TOMMY FACTORY",            slug: "tommy-factory",            imagePath: "/images/18.jpg", client: "TOMMY HX",    tags: ["EDITORIAL", "DIGITAL", "WEB"],      year: 2021 },
  { title: "OPEN YOUR WORLD",          slug: "open-your-world",          imagePath: "/images/19.jpg", client: "HEINEKEN",    tags: ["CAMPAIGN", "FILM", "OOH"],          year: 2021 },
  { title: "SURFACE PRO LAUNCH",       slug: "surface-pro-launch",       imagePath: "/images/20.jpg", client: "MICROSOFT",   tags: ["PRODUCT", "UI/UX", "MOTION"],       year: 2021 },
  { title: "NEON JUNGLE REBRAND",      slug: "neon-jungle-rebrand",      imagePath: "/images/21.jpg", client: "RIOT GAMES",  tags: ["IDENTITY", "MOTION", "GAMING"],     year: 2021 },
  { title: "ABSOLUT CANVAS",          slug: "absolut-canvas",           imagePath: "/images/22.jpg", client: "PERNOD",      tags: ["ILLUSTRATION", "OOH", "CAMPAIGN"],  year: 2021 },
  { title: "CLIMATE PLEDGE ARENA",     slug: "climate-pledge-arena",     imagePath: "/images/23.jpg", client: "AMAZON",      tags: ["IDENTITY", "ENVIRONMENTAL"],        year: 2021 },
  { title: "GLOW SKINCARE LAUNCH",     slug: "glow-skincare-launch",     imagePath: "/images/24.jpg", client: "AESOP",       tags: ["PACKAGING", "DIGITAL", "PRINT"],    year: 2020 },
  { title: "HYPER SPORT SS21",         slug: "hyper-sport-ss21",         imagePath: "/images/25.jpg", client: "UNDER ARMOUR",tags: ["CAMPAIGN", "MOTION", "SOCIAL"],     year: 2020 },
  { title: "PIXEL ART WORLD",          slug: "pixel-art-world",          imagePath: "/images/26.jpg", client: "GOOGLE",      tags: ["INTERACTIVE", "WEB", "3D"],         year: 2020 },
  { title: "BORN FREE COLLECTION",     slug: "born-free-collection",     imagePath: "/images/27.jpg", client: "PATAGONIA",   tags: ["EDITORIAL", "PRINT", "CAMPAIGN"],   year: 2020 },
  { title: "ULTRABOOST 22 REVEAL",     slug: "ultraboost-22-reveal",     imagePath: "/images/28.jpg", client: "ADIDAS",      tags: ["3D", "FILM", "PRODUCT"],            year: 2020 },
  { title: "NESCAFÉ RITUAL",           slug: "nescafe-ritual",           imagePath: "/images/29.jpg", client: "NESTLÉ",      tags: ["CAMPAIGN", "FILM", "SOCIAL"],       year: 2020 },
  { title: "PHANTOM OVERDRIVE",        slug: "phantom-overdrive",        imagePath: "/images/30.jpg", client: "ROLLS-ROYCE", tags: ["FILM", "3D", "LUXURY"],             year: 2020 },
  { title: "METAVERSE FESTIVAL",       slug: "metaverse-festival",       imagePath: "/images/31.jpg", client: "FORTNITE",    tags: ["INTERACTIVE", "3D", "EVENT"],       year: 2020 },
  { title: "VAULT COLLECTION",         slug: "vault-collection",         imagePath: "/images/32.jpg", client: "SUPREME",     tags: ["EDITORIAL", "PRODUCT", "DIGITAL"],  year: 2019 },
  { title: "BLUE LABEL REDESIGN",      slug: "blue-label-redesign",      imagePath: "/images/33.jpg", client: "JOHNNIE W.",  tags: ["PACKAGING", "IDENTITY"],            year: 2019 },
  { title: "COSMIC RETAIL",            slug: "cosmic-retail",            imagePath: "/images/34.jpg", client: "GLOSSIER",    tags: ["SPATIAL", "IDENTITY", "DIGITAL"],   year: 2019 },
  { title: "DARKROOM SERIES",          slug: "darkroom-series",          imagePath: "/images/35.jpg", client: "LEICA",       tags: ["EDITORIAL", "PRINT"],               year: 2019 },
  { title: "FORMULA E SEASON 6",       slug: "formula-e-season-6",       imagePath: "/images/36.jpg", client: "ABB FIA",     tags: ["MOTION", "IDENTITY", "CAMPAIGN"],   year: 2019 },
  { title: "REWILD CAMPAIGN",          slug: "rewild-campaign",          imagePath: "/images/37.jpg", client: "WWF",         tags: ["CAMPAIGN", "OOH", "PRINT"],         year: 2019 },
  { title: "HORIZON TYPEFACE",         slug: "horizon-typeface",         imagePath: "/images/38.jpg", client: "MONOTYPE",    tags: ["TYPE DESIGN", "IDENTITY"],          year: 2019 },
  { title: "KINETIC BRANDING",         slug: "kinetic-branding",         imagePath: "/images/39.jpg", client: "WIRED",       tags: ["MOTION", "IDENTITY", "EDITORIAL"],  year: 2019 },
  { title: "CRYSTAL PAVILION",         slug: "crystal-pavilion",         imagePath: "/images/40.jpg", client: "SWAROVSKI",   tags: ["SPATIAL", "3D", "LUXURY"],          year: 2019 },
  { title: "SOUND IDENTITY",           slug: "sound-identity",           imagePath: "/images/41.jpg", client: "DOLBY",       tags: ["IDENTITY", "MOTION", "DIGITAL"],    year: 2018 },
  { title: "FLORA PACKAGING",          slug: "flora-packaging",          imagePath: "/images/42.jpg", client: "HERMÈS",      tags: ["PACKAGING", "ILLUSTRATION"],        year: 2018 },
  { title: "DEEP DIVE CAMPAIGN",       slug: "deep-dive-campaign",       imagePath: "/images/43.jpg", client: "NATIONAL GEO",tags: ["EDITORIAL", "FILM", "OOH"],         year: 2018 },
  { title: "ALTITUDE APPAREL",         slug: "altitude-apparel",         imagePath: "/images/44.jpg", client: "THE NORTH FACE",tags: ["CAMPAIGN", "MOTION", "RETAIL"],   year: 2018 },
  { title: "PRISM LAUNCH",             slug: "prism-launch",             imagePath: "/images/45.jpg", client: "SONY",        tags: ["PRODUCT", "FILM", "DIGITAL"],       year: 2018 },
  { title: "HARVEST IDENTITY",         slug: "harvest-identity",         imagePath: "/images/46.jpg", client: "WHOLE FOODS", tags: ["IDENTITY", "PACKAGING", "PRINT"],   year: 2018 },
  { title: "PHANTOM TYPE",             slug: "phantom-type",             imagePath: "/images/47.jpg", client: "FENDER",      tags: ["TYPE DESIGN", "IDENTITY", "MUSIC"], year: 2018 },
  { title: "CARBON OFFSET BRAND",      slug: "carbon-offset-brand",      imagePath: "/images/48.jpg", client: "TESLA",       tags: ["IDENTITY", "MOTION", "WEB"],        year: 2018 },
  { title: "JADE COLLECTION",          slug: "jade-collection",          imagePath: "/images/49.jpg", client: "CARTIER",     tags: ["FILM", "LUXURY", "CAMPAIGN"],       year: 2018 },
  { title: "GRIDLOCK MAGAZINE",        slug: "gridlock-magazine",        imagePath: "/images/50.jpg", client: "SELF PROMO",  tags: ["EDITORIAL", "TYPOGRAPHY", "PRINT"], year: 2018 },
  { title: "SMOKE & MIRRORS",          slug: "smoke-and-mirrors",        imagePath: "/images/51.jpg", client: "ISSEY M.",    tags: ["CAMPAIGN", "FILM", "FRAGRANCE"],    year: 2017 },
  { title: "NEON NOIR EDITORIAL",      slug: "neon-noir-editorial",      imagePath: "/images/52.jpg", client: "DAZED",       tags: ["EDITORIAL", "ART DIRECTION"],       year: 2017 },
  { title: "PURE FORM IDENTITY",       slug: "pure-form-identity",       imagePath: "/images/53.jpg", client: "MUJI",        tags: ["IDENTITY", "PACKAGING", "SPATIAL"], year: 2017 },
  { title: "ATLAS WAYFINDING",         slug: "atlas-wayfinding",         imagePath: "/images/54.jpg", client: "HEATHROW",    tags: ["WAYFINDING", "IDENTITY", "PRINT"],  year: 2017 },
  { title: "VELVET UNDERGROUND",       slug: "velvet-underground",       imagePath: "/images/55.jpg", client: "WARNER",      tags: ["EDITORIAL", "MUSIC", "PRINT"],      year: 2017 },
  { title: "STORMCLOUD GAMING",        slug: "stormcloud-gaming",        imagePath: "/images/56.jpg", client: "NVIDIA",      tags: ["IDENTITY", "MOTION", "GAMING"],     year: 2017 },
  { title: "LUNAR NEW YEAR",           slug: "lunar-new-year",           imagePath: "/images/57.jpg", client: "ALIBABA",     tags: ["CAMPAIGN", "ILLUSTRATION", "SOCIAL"],year: 2017 },
  { title: "DESERT BLOOM",             slug: "desert-bloom",             imagePath: "/images/58.jpg", client: "BOTTEGA V.",  tags: ["EDITORIAL", "FILM", "FASHION"],     year: 2017 },
  { title: "SONIC FUTURES",            slug: "sonic-futures",            imagePath: "/images/59.jpg", client: "BOSE",        tags: ["PRODUCT", "FILM", "DIGITAL"],       year: 2017 },
  { title: "IRON ATLAS",               slug: "iron-atlas",               imagePath: "/images/60.jpg", client: "GE",          tags: ["IDENTITY", "MOTION", "INDUSTRIAL"], year: 2017 },
  { title: "STUDIO REBRAND",           slug: "studio-rebrand",           imagePath: "/images/61.jpg", client: "A24",         tags: ["IDENTITY", "MOTION", "FILM"],       year: 2016 },
  { title: "NORTHERN LIGHTS",          slug: "northern-lights",          imagePath: "/images/62.jpg", client: "AURORA",      tags: ["INTERACTIVE", "WEB", "DIGITAL"],    year: 2016 },
  { title: "CRAFT SERIES",             slug: "craft-series",             imagePath: "/images/63.jpg", client: "PATEK P.",    tags: ["PRINT", "LUXURY", "EDITORIAL"],     year: 2016 },
  { title: "NEON ORIGINS",             slug: "neon-origins",             imagePath: "/images/64.jpg", client: "URBAN DECAY", tags: ["CAMPAIGN", "SOCIAL", "BEAUTY"],     year: 2016 },
  { title: "GRID CITY REBRAND",        slug: "grid-city-rebrand",        imagePath: "/images/65.jpg", client: "UBER",        tags: ["IDENTITY", "MOTION", "WEB"],        year: 2016 },
  { title: "MINERAL IDENTITY",         slug: "mineral-identity",         imagePath: "/images/66.jpg", client: "GLOSSIER",    tags: ["PACKAGING", "IDENTITY"],            year: 2016 },
  { title: "HYPERCOLOR CAMPAIGN",      slug: "hypercolor-campaign",      imagePath: "/images/67.jpg", client: "PANTONE",     tags: ["CAMPAIGN", "PRINT", "IDENTITY"],    year: 2016 },
  { title: "TUNDRA APPAREL",           slug: "tundra-apparel",           imagePath: "/images/68.jpg", client: "CANADA GOOSE",tags: ["CAMPAIGN", "EDITORIAL", "OOH"],     year: 2016 },
  { title: "ZERO WASTE BRAND",         slug: "zero-waste-brand",         imagePath: "/images/69.jpg", client: "PANGAIA",     tags: ["IDENTITY", "PACKAGING", "DIGITAL"], year: 2016 },
  { title: "PARALLAX WEB",             slug: "parallax-web",             imagePath: "/images/70.jpg", client: "AWWWARDS",    tags: ["WEB", "INTERACTIVE", "MOTION"],     year: 2016 },
  { title: "PULSE MOTION SYSTEM",      slug: "pulse-motion-system",      imagePath: "/images/71.jpg", client: "SPOTIFY",     tags: ["MOTION", "IDENTITY", "SYSTEM"],     year: 2015 },
  { title: "ORIGIN STORY",             slug: "origin-story",             imagePath: "/images/72.jpg", client: "LEGO",        tags: ["CAMPAIGN", "3D", "FILM"],           year: 2015 },
  { title: "URBAN GRADIENT",           slug: "urban-gradient",           imagePath: "/images/73.jpg", client: "CONVERSE",    tags: ["CAMPAIGN", "SOCIAL", "OOH"],        year: 2015 },
  { title: "VOID TYPEFACE",            slug: "void-typeface",            imagePath: "/images/74.jpg", client: "SELF PROMO",  tags: ["TYPE DESIGN", "IDENTITY"],          year: 2015 },
  { title: "WAVE SYSTEM",              slug: "wave-system",              imagePath: "/images/75.jpg", client: "BANG & OLUFSEN",tags: ["IDENTITY", "PRODUCT", "DIGITAL"], year: 2015 },
  { title: "RAW MATERIAL",             slug: "raw-material",             imagePath: "/images/76.jpg", client: "STONE ISLAND",tags: ["EDITORIAL", "CAMPAIGN", "FASHION"], year: 2015 },
  { title: "PARALLEL WORLDS",          slug: "parallel-worlds",          imagePath: "/images/77.jpg", client: "HBO",         tags: ["TITLE SEQ", "MOTION", "VFX"],       year: 2015 },
  { title: "IVORY TOWER LAUNCH",       slug: "ivory-tower-launch",       imagePath: "/images/78.jpg", client: "DIOR",        tags: ["FILM", "LUXURY", "FRAGRANCE"],      year: 2015 },
  { title: "CIRCUIT BREAKER",          slug: "circuit-breaker",          imagePath: "/images/79.jpg", client: "INTEL",       tags: ["IDENTITY", "MOTION", "TECH"],       year: 2015 },
  { title: "HALO REBRAND",             slug: "halo-rebrand",             imagePath: "/images/80.jpg", client: "XBOX",        tags: ["IDENTITY", "GAMING", "MOTION"],     year: 2015 },
  { title: "PAPER ARCHITECTURE",       slug: "paper-architecture",       imagePath: "/images/81.jpg", client: "ZAHA H.",     tags: ["PRINT", "EDITORIAL", "SPATIAL"],    year: 2014 },
  { title: "DEPTH CHARGE",             slug: "depth-charge",             imagePath: "/images/82.jpg", client: "RED BULL",    tags: ["CAMPAIGN", "FILM", "SOCIAL"],       year: 2014 },
  { title: "MONO SYSTEM",              slug: "mono-system",              imagePath: "/images/83.jpg", client: "BRAUN",       tags: ["IDENTITY", "PRODUCT", "PRINT"],     year: 2014 },
  { title: "OBSIDIAN IDENTITY",        slug: "obsidian-identity",        imagePath: "/images/84.jpg", client: "BLACK CROW",  tags: ["IDENTITY", "PACKAGING"],            year: 2014 },
  { title: "FLUX TITLE SEQUENCE",      slug: "flux-title-sequence",      imagePath: "/images/85.jpg", client: "FX",          tags: ["TITLE SEQ", "MOTION", "TYPE"],      year: 2014 },
  { title: "FIELD NOTES SS14",         slug: "field-notes-ss14",         imagePath: "/images/86.jpg", client: "COS",         tags: ["EDITORIAL", "FASHION", "PRINT"],    year: 2014 },
  { title: "GENESIS BRAND SYSTEM",     slug: "genesis-brand-system",     imagePath: "/images/87.jpg", client: "GENESIS",     tags: ["IDENTITY", "MOTION", "AUTOMOTIVE"], year: 2014 },
];
